unbind C-b
set -g prefix C-s

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

set -g mouse on
set -g base-index 1
set -g pane-base-index 1

set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -g focus-events on
set -as terminal-overrides ",*:Tc"

set-option -g status-position top
set -g status-style 'bg=#333333 fg=#00FFFF'
set -g status-left "[#S] "
set -g status-right "%H:%M | %d-%b"
set -g status-left-length 40
set -g status-right-length 80
setw -g window-status-format "#I:#W "
setw -g window-status-current-format "#[fg=#FFFF00,bold]#I:#W "

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

unbind %
bind | split-window -h

unbind '"'
bind _ split-window -v

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
