edit-espanso() {
    case $1 in
        nvim)  nvim ~/.config/espanso/match/base.yml ;;
        geany) geany ~/.config/espanso/match/base.yml ;;
        *)     echo "Usage: edit-expander [nvim|geany]" ;;
    esac
}

gcp(){
    git add . && git commit -m "$1" && git push
}

rj() {
    javac "$1"
    java "${1%.*}"
}

lgbr(){
     ddcutil --bus 3 setvcp 10 "$1"
}

bookmarksToHtml(){
    cat ~/dotfiles/style.html > ~/github/bookmarks/index.html 

    cmark --to html ~/dotfiles/bookmarks.md >> ~/github/bookmarks/index.html

    cd ~/github/bookmarks

    git add . 

    git commit -m "updated bookmarks - this is autogenerated - don't mind it much"

    git push -u origin main
}

jnew() {
    local file="$1"
    local class="${file%.java}"

    cat > "$file" <<EOF
public class $class {
    
}
EOF
}

dsa() {
    tmux new-session -d -s dsa -c ~/dsa -n 'nvim'

    tmux new-window -t dsa:2 -c ~/dsa -n 'terminal'

    tmux select-window -t dsa:1

    tmux attach-session -t dsa
}

spring(){
    TARGET_DIR=~/spring

    tmux new-session -d -s spring -c "$TARGET_DIR" -n 'nvim'

    tmux new-window -t spring:2 -c "$TARGET_DIR" -n 'server'

    tmux split-window -h -c $TARGET_DIR

    tmux select-window -t spring:1

    tmux attach-session -t spring
}

dotfiles() {
    cp -r $1 ~/Documents/dotfiles/
}

sop(){ 
    file="$(find)"
    [ -n "$file" ] && okular "$file"
}

cdJ() {
    local dir
    dir=$(fd -t d -H | fzf) || return
    cd "$dir"
    clear
    ls
    ccp
}

cdj() {
    local dir
    dir=$(fd -t d | fzf) || return
    cd "$dir"
    ls
    ccp
}

animated_wallpaper(){
    xwinwrap -fs -fdt -ni -b -nf -ov -- mpv -wid WID --loop --no-audio $1
}


