edit-espanso() {
    case $1 in
        nvim)  nvim ~/.config/espanso/match/base.yml ;;
        geany) geany ~/.config/espanso/match/base.yml ;;
        *)     echo "Usage: edit-expander [nvim|geany]" ;;
    esac
}

function y() {
    local tmp cwd; tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
    command yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd" || builtin true
    command rm -f -- "$tmp"
}

gcp(){
    git add . && git commit -m "$1" && git push
}

rj() {
    javac "$1"
    java "${1%.*}"
}

lgbr(){
    ddcutil --bus 3 setvcp 10 "$1"
}

bookmarksToHtml(){
    cat ~/dotfiles/style.html > ~/github/bookmarks/index.html 

    cmark --to html ~/dotfiles/bookmarks.md >> ~/github/bookmarks/index.html

    cd ~/github/bookmarks

    git add . 

    git commit -m "updated bookmarks - this is autogenerated - don't mind it much"

    git push -u origin main
}

jnew() {
    local file="$1"
    local class="${file%.java}"

    cat > "$file" <<EOF
public class $class {

}
EOF
}

dsa() {
    tmux new-session -d -s dsa -c ~/dsa -n 'nvim'

    tmux new-window -t dsa:2 -c ~/dsa -n 'terminal'

    tmux select-window -t dsa:1

    tmux attach-session -t dsa
}

practice() {
    tmux new-session -d -s practice -n 'nvim'

    tmux new-window -t practice:2 -n 'terminal'

    tmux select-window -t practice:1

    tmux attach-session -t practice
}

spring(){
    TARGET_DIR=~/spring

    tmux new-session -d -s spring -c "$TARGET_DIR" -n 'nvim'

    tmux new-window -t spring:2 -c "$TARGET_DIR" -n 'server'

    tmux split-window -h -c $TARGET_DIR

    tmux select-window -t spring:1

    tmux attach-session -t spring
}

dotfiles() {
    cp -r $1 ~/Documents/dotfiles/
}

sop(){ 
    file="$(find)"
    [ -n "$file" ] && okular "$file"
}

cdJ() {
    local dir
    dir=$(fd -t d -H | fzf) || return
    cd "$dir"
    clear
    ls
    ccp
}

cdj() {
    local dir
    dir=$(fd -t d | fzf) || return
    cd "$dir"
    ls
    ccp
}

animated_wallpaper(){
    xwinwrap -fs -fdt -ni -b -nf -ov -- mpv -wid WID --loop --no-audio $1
}


cc() {
    local file="$1"
    local output="${file%.c}.out"

    gcc "$file" -o "$output" && "./$output"
}
