
[General]
# Password mask character
passwordCharacter=*
# Mask password characters or not ("true" or "false")
passwordMask=true
# value "1" is all display width, "0.5" is a half of display width etc.
passwordInputWidth=0.5
# Background color of password input
#passwordInputBackground=#1e1e2e

# Radius of password input corners
passwordInputRadius=50
# "true" for visible cursor, "false"
passwordInputCursorVisible=false
# Font size of password (in points)
passwordFontSize=26
passwordCursorColor=#cdd6f4
passwordTextColor=#a1a1a5

# Show or not sessions choose label
showSessionsByDefault=true
# Font size of sessions choose label (in points).
sessionsFontSize=10

# Show or not users choose label
showUsersByDefault=false
# Font size of users choose label (in points)
usersFontSize=48

# Path to background image
background=img.jpg
# Or use just one color
backgroundFill=#1e1e2e
# Fill mode for image background
# Value must be on of: aspect, fill, tile, pad
backgroundFillMode=aspect

# Default text color for all labels
basicTextColor=#a1a1a5

# Radius of background blur
blurRadius=
