# ============================================
#   i3 Appearance — Catppuccin Mocha
# ============================================

# Font
font pango:CaskaydiaCove Nerd Font Mono 10

# ── Gaps ─────────────────────────────────────
gaps inner 0
gaps outer 0

# ── Borders ──────────────────────────────────
default_border normal 3
default_floating_border normal 3
hide_edge_borders none

# ── Colors ───────────────────────────────────
# class                  border    bg        text      indicator child_border
client.focused           #cba6f7   #cba6f7   #1e1e2e   #f5c2e7   #cba6f7
client.focused_inactive  #313244   #313244   #cdd6f4   #313244   #313244
client.unfocused         #1e1e2e   #1e1e2e   #6c7086   #1e1e2e   #1e1e2e
client.urgent            #f38ba8   #f38ba8   #1e1e2e   #f38ba8   #f38ba8
client.placeholder       #1e1e2e   #1e1e2e   #cdd6f4   #1e1e2e   #1e1e2e
client.background        #1e1e2e
