# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id picom --config ~/.config/picom/picom.conf --no-ewmh-fullscreen 2>/dev/null
exec --no-startup-id copyq
exec --no-startup-id blueman-applet
exec --no-startup-id espanso start
exec --no-startup-id setxkbmap -option caps:none
exec --no-startup-id numlockx on
exec --no-startup-id dunst -config ~/.config/dunst/dunstrc

exec_always --no-startup-id feh --bg-scale ~/Downloads/Wallpapers/car-with-full-moon-background.jpg
exec_always --no-startup-id killall polybar
exec_always --no-startup-id ~/.config/polybar/launch_polybar.sh
