
# start a terminal
# bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Return exec alacritty
bindsym $mod+ctrl+Return exec alacritty --working-directory "$(xcwd)"
bindsym $mod+b exec brave
bindsym $mod+Shift+s exec --no-startup-id flameshot gui
bindsym $mod+Shift+y exec brave --new-window https://www.youtube.com/
bindsym MOD1+t exec brave --app=https://www.notion.so/
bindsym Ctrl+MOD1+t exec brave --app=https://chatgpt.com/?temporary-chat=true
bindsym Ctrl+MOD1+g exec brave --app=https://gemini.google.com/app
bindsym Ctrl+MOD1+w exec brave --app=https://web.whatsapp.com/
bindsym Ctrl+MOD1+p exec --no-startup-id ~/scripts/doubtClearance-setup.sh
bindsym Mod1+v exec copyq toggle
bindsym $mod+Shift+b exec alacritty -e nvim ~/dotfiles/bookmarks.md


# kill focused window
bindsym $mod+q kill

# emoji picker
bindsym Mod1+e exec /home/shivansh/.local/bin/rofimoji --action type copy

# Alt + Space -> App launcher
bindcode Mod1+65 exec "rofi -modi drun,calc:qalc -show drun"

bindsym Ctrl+Shift+Escape exec systemctl suspend


# change focus
bindsym $mod+h focus left
bindsym $mod+j focus up
bindsym $mod+k focus down
bindsym $mod+l focus right
# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move up
bindsym $mod+Shift+k move down 
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+g split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child
